global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'targets'
    static_configs:
      - targets: ['host.docker.internal:3001']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['host.docker.internal:9216']